// AUTO-GENERATED by scripts/extractCourseMapPositions.ts
// Source: public/courseMap.svg  (Excalidraw handmade layout)
// DO NOT EDIT manually — re-run: npm run extract:course-map
//
// Coordinates are ReactFlow top-left positions derived from the SVG centre:
//   rfX = svgCenterX - 84   (NODE_W=168)
//   rfY = svgCenterY - 37   (NODE_H=74)

export interface CoursePosition {
  x: number;
  y: number;
}

export const GENERATED_COURSE_POSITIONS: Record<string, CoursePosition> = {
  "CSCE 1030": { x: 851, y: 53 },
  "CSCE 1040": { x: 831, y: 296 },
  "CSCE 2100": { x: 1376, y: 674 },
  "CSCE 2110": { x: 858, y: 611 },
  "CSCE 2610": { x: 1962, y: 771 },
  "CSCE 3444": { x: 731, y: 1038 },
  "CSCE 3530": { x: 870, y: 1735 },
  "CSCE 3550": { x: 134, y: 1031 },
  "CSCE 3600": { x: 1361, y: 975 },
  "CSCE 4010": { x: 1371, y: 1444 },
  "CSCE 4110": { x: 825, y: 1448 },
  "CSCE 4115": { x: 267, y: 1760 },
  "CSCE 4201": { x: 1594, y: 1769 },
  "CSCE 4210": { x: 1597, y: 1932 },
  "CSCE 4230": { x: 2008, y: 1749 },
  "CSCE 4290": { x: 2011, y: 1922 },
  "CSCE 4350": { x: 1630, y: 2092 },
  "CSCE 4430": { x: 256, y: 1930 },
  "CSCE 4460": { x: 2022, y: 2070 },
  "CSCE 4600": { x: 891, y: 1919 },
  "CSCE 4650": { x: 554, y: 2109 },
  "CSCE 4901": { x: 2646, y: 1373 },
  "CSCE 4902": { x: 2601, y: 1763 },
  "MATH 1710": { x: 1421, y: 51 },
  "MATH 1720": { x: 1790, y: 310 },
  "MATH 2700": { x: 2389, y: 749 },
  "TECM 2700": { x: 2463, y: 317 },
};
